### ISSUE TITLE
Example command

### ISSUE THREAD

**Issue by grahamnaylormrc** [tlrh314/misc#4]
Do you have an example command to turn relays on? I have converted the python to python 3 (Print and except commands adjusted) but am getting errors when I try:
python3 communicate_with_vm201 '192.168.0.100' 9760 'XXXXX' 'YYYY' 'CMD_ON 4'
gives TypeError: ord() expected string of length 1, but int found

**Comment by tlrh314** [comment]
Hi grahamnaylormrc,

The (example) commands to turn relays on/off sit in communicate_with_vm201.py, so you're already using them.

From the looks of the error message you'll have to further port the code to Python 3, in particular calls to the `ord` function in the class TCPPacketHandler. Perhaps [this post on StackOverflow](https://stackoverflow.com/questions/39103164) might help. 

Unfortunately my vm201 is not in use at the moment and I did not implement tests, so I'm afraid I can't be of much help. Good luck and thx for using the code!

A pull request would be appreciated once you've figured it out :-).

Cheers,
Timo
